import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

//#region ----- fonts
const labelAtribute = localFont({
    src: "./fonts/Jaini-Regular.ttf",
    variable: "--label-atribute",
});

const contentInputAtribute = localFont({
    src: "./fonts/Amita-Regular.ttf",
    variable: "--content-input-atribute"
})
//#endregion

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${labelAtribute.variable} ${contentInputAtribute.variable}`}>
        {children}
      </body>
    </html>
  );
}
